schema-version: v2
kind: plugin
metadata:
  name: java-spring-data-jpa-plugin
  display-name: java-spring-data-jpa-plugin
  description: Plugin to enable and configure Spring Data JPA in Spring Boot Java applications
  version: 1.0.0
  picture: plugin.png
spec:
  type: app
  compatibility:
    - maven
    - application.yaml
    - java
    - spring
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
  inputs:
    - label: Choose one database (RDBMS)
      name: database_name
      type: text
      items:
        - H2
        - PostgreSQL
        - MySQL
      help: If you don't have an infra for your database, you can use the H2 since it's an in-memory relational database.
  computed-inputs:
    database_name_formatted: "{{database_name | lower}}"
    # Does not work anymore. It seems like the inputs created at the before-input hook are not accessible via Jinja's EL.
    # path_main_code_directory: "{{path_main_code_directory | group_id_folder}}"
    # path_test_code_directory: "{{path_test_code_directory | group_id_folder}}"
    
  hooks:
    ##
    # Edit application.yaml
    ##
    - type: edit
      path: src/main/resources/application.yaml
      trigger: after-render    
      changes:
        - search:
            string: "spring:"
            insert-after:
              snippet: snippets/snippet-application.yaml.jinja
            when:
              not-exists: "datasource:"
    ##
    # Edit application-test.yaml
    ##
    - type: edit
      path: src/test/resources/application-test.yaml
      trigger: after-render    
      changes:
        - search:
            string: "spring:"
            insert-after:
              snippet: snippets/snippet-application-test.yaml.jinja
            when:
              not-exists: "datasource:"
    ##
    # Edit pom.xml
    ##
    - type: edit
      path: pom.xml
      trigger: after-render    
      changes:
        - search:
            string: "</dependencies>"
            insert-before:
              snippet: snippets/snippet-pom.xml.jinja
            when:
              not-exists-snippet: snippets/snippet-pom.xml.jinja
    ##
    # Create or edit docker-compose.yaml
    ##
    - type: render-templates
      trigger: after-render
      path: snippets/docker-postgresql
      condition:
        variable: database_name_formatted
        operator: ==
        value: postgresql

    - type: render-templates
      trigger: after-render
      path: snippets/docker-mysql
      condition:
        variable: database_name_formatted
        operator: ==
        value: mysql
    ##
    # Create directory samples code
    ##
    - type: run-script
      trigger: before-input
      script: scripts/open-pom.py
    ##
    # Create samples code
    ##
    - type: render-templates
      trigger: after-render
      path: snippets/samples